// Generated by tools/generate-contract.mjs. Do not edit by hand.
export type ViewId = "side" | "topdown" | "isometric";
export type ActionId = "idle" | "walk" | "run" | "jump" | "lantern";
export type ImageModelId = "gemini-2.5-flash-image" | "gemini-3.1-flash-image-preview" | "gemini-3.0-pro-image-preview";
export declare const CONTRACT_VERSION: "1.0.0";
export declare const FIXED_FPS: 8;
export declare const viewLabels: Record<ViewId, readonly [string, string]>;
export declare const actionOrder: readonly ActionId[];
export declare const actionLabels: Record<ActionId, readonly [string, string]>;
export declare const actionLoops: Record<ActionId, boolean>;
