import assert from 'node:assert/strict';
import { readdir, readFile } from 'node:fs/promises';
import test from 'node:test';

import {
  FIXED_FPS,
  actionFrameCounts,
  actionLoops,
  actionOrder,
  cocosFrameNames,
  cocosRuntime,
} from '../asset-lab/data/generated-contract.js';

const root = new URL('..', import.meta.url);

test('Cocos runtime mappings follow the generated Windup contract and real assets', async () => {
  assert.equal(FIXED_FPS, 8);
  assert.ok(Object.keys(cocosRuntime.actions).length > 0);

  const resourceDirectory = new URL(`../assets/resources/${cocosRuntime.resourcePath}/`, import.meta.url);
  const entries = await readdir(resourceDirectory);
  const assetNames = new Set(entries
    .filter((name) => name.endsWith('.png.meta'))
    .map((name) => name.slice(0, -'.png.meta'.length)));

  for (const [runtimeAction, profile] of Object.entries(cocosRuntime.actions)) {
    assert.ok(actionOrder.includes(profile.contractAction), `${runtimeAction} must target a contract action`);
    assert.equal(typeof actionLoops[profile.contractAction], 'boolean');

    const frameNames = cocosFrameNames(runtimeAction);
    assert.equal(frameNames.length, profile.frameOrder.length);
    assert.equal(new Set(frameNames).size, frameNames.length);
    for (const frameName of frameNames) {
      assert.match(frameName, /^[a-z][a-z0-9-]*-\d{2}$/);
      assert.ok(assetNames.has(frameName), `${runtimeAction} maps missing Cocos frame ${frameName}`);
    }
  }

  for (const starterAction of ['idle', 'walk']) {
    const profiles = Object.values(cocosRuntime.actions).filter((profile) => profile.contractAction === starterAction);
    assert.ok(profiles.length > 0, `${starterAction} must have a Cocos runtime mapping`);
  }

  assert.equal(actionFrameCounts.walk, 8);
});

test('GameRoot consumes generated values and contains no frame-name magic strings', async () => {
  const source = await readFile(new URL('../assets/scripts/GameRoot.ts', import.meta.url), 'utf8');
  assert.match(source, /from '\.\/generated-contract'/);
  assert.match(source, /FIXED_FPS/);
  assert.match(source, /cocosFrameNames/);
  assert.doesNotMatch(source, /\b[a-z][a-z0-9-]*-\d{2}\b/);

  const generated = await readFile(new URL('../assets/scripts/generated-contract.ts', import.meta.url), 'utf8');
  assert.match(generated, /Generated by tools\/generate-contract\.mjs/);
  assert.match(generated, /COCOS_RUNTIME_ACTIONS/);
});
