// Generated by tools/generate-contract.mjs. Do not edit by hand.
export const CONTRACT_VERSION = "1.2.0" as const;
export const FIXED_FPS = 8 as const;
export const ACTION_IDS = ["idle","walk","run","jump","lantern"] as const;
export type ActionId = typeof ACTION_IDS[number];
export const ACTION_LOOPS: Record<ActionId, boolean> = {
  "idle": true,
  "walk": true,
  "run": true,
  "jump": false,
  "lantern": false
};
export const ACTION_FRAME_COUNTS: Record<ActionId, number> = {
  "idle": 8,
  "walk": 8,
  "run": 8,
  "jump": 8,
  "lantern": 8
};
export const COCOS_RESOURCE_PATH = "character/frames" as const;
export const COCOS_RUNTIME_ACTIONS = {
  "idle": {
    "contractAction": "idle",
    "assetAction": "idle",
    "frameOrder": [
      1,
      2,
      3,
      4
    ]
  },
  "walk": {
    "contractAction": "walk",
    "assetAction": "walk",
    "frameOrder": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8
    ]
  },
  "lantern-idle": {
    "contractAction": "lantern",
    "assetAction": "lantern-walk",
    "frameOrder": [
      3
    ]
  },
  "lantern-walk": {
    "contractAction": "lantern",
    "assetAction": "lantern-walk",
    "frameOrder": [
      3,
      1,
      4,
      2
    ]
  }
} as const;
export type CocosRuntimeActionId = keyof typeof COCOS_RUNTIME_ACTIONS;
export function isActionId(value: string): value is ActionId {
  return (ACTION_IDS as readonly string[]).includes(value);
}
export function cocosFrameNames(action: CocosRuntimeActionId): string[] {
  const profile = COCOS_RUNTIME_ACTIONS[action];
  return profile.frameOrder.map((frame) => profile.assetAction + '-' + String(frame).padStart(2, '0'));
}
